development:
  adapter: mysql2
  encoding: utf8
  database: brokenlifts_development
  pool: 5
  username: root
  password:
  reconnect: false
  socket: /tmp/mysql.sock


test:
  adapter: mysql2
  encoding: utf8
  database: brokenlifts_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock


production:
  adapter: mysql2
  encoding: utf8
  database: brokenlifts_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

